### ISSUE TITLE
Could not find artifact ...

### ISSUE THREAD

**Issue by stepqom** [jtulach/leaflet4j#3]
I tried to run the demo on the iPad Simulator, but I get this error:

Could not find artifact org.apidesign.brwsr:ibrwsr:jar:0.8.3 in central (https://repo1.maven.org/maven2)

Obviously the dependency will  not be solved. But why? On http://search.maven.org/ you will find the dependency, but with https://repo1.maven.org/maven2/org/apidesign/brwsr/ibrwsr/0.8.3/ibrwsr-0.8.3.jar you get an 404. The same for dlvkbrwsr. And the same on https://maven.java.net/content/repositories/snapshots/org/apidesign/. No brwsr at all.

Where is my mistake?

And when I try to create a project with Netbeans 8.0.1 (HTML5 with Java Application Logic) there is no Step Android nor iOS.

**Comment by jtulach** [comment]
The main repo has been moved to DukeScript, try to use its getting started tutorial: https://dukescript.com/getting_started.html
Your experience should be better.

Sorry for the troubles.
