### ISSUE TITLE
text showing incorrectly while loadingmap on javafx

### ISSUE THREAD

**Issue by devidatta45** [jtulach/leaflet4j#6]
i am trying to load map on javafx using leaflet4j library. its loading correctly. but i have two issues. 

1.its not able to load the map in the background.
2.the texts on the screen are not coming properly.

i am attaching the file for referrence.
![texterror](https://cloud.githubusercontent.com/assets/14850980/13878068/da4be6e4-ed34-11e5-90d4-ff1343af90ee.png)

please help me on this. thanks in advance.

Datta

**Comment by jtulach** [comment]
Hard to say what is wrong. Try to debug your application and/or observe the output messages.
